### PR TITLE
Restore out of source builds

### PR DESCRIPTION
**Pull request by paul-pearce**
Addresses #407

We now once again support out of source builds. I added notes on performing an out of source build to the readme.

### CODE REVIEW

**Comment by paul-pearce** [comment]
It's worth pointing out that `cmake .` throws a ton of files into the source directory that you can only get rid of by either 1) deleting everything from `.gitignore` or 2) deleting the repo and recloning. It's a bit of a mess. There's no notion of `cmake clean` in cmake, and most recommend out of source builds.

It's worth considering if we want to recommend out of source builds by default. The main drawback is it makes the install instructions less awesome, as the cmake options for out of source builds are undocumented.

**Comment by paul-pearce** [comment]
@zakird nor do I. Should I go ahead and merge or do we think @dadrian might not understand cmake less than us? 

(I also added `build/` to the gitignore so if you follow the readme it doesn't try to commit the build dir.)

**Comment by dadrian** [comment]
Out of source builds are traditionally done by doing `cd /some/random/path; cmake /path/to/zmap`. Does this work?

**Comment by paul-pearce** [comment]
@dadrian, interesting. The (poor) documentation I found indicated otherwise.

Yes, that works too.

**Comment by paul-pearce** [comment]
My rationale for including that is I think we should actually encourage out of source builds. 

It's a bit crazy that once you type `cmake .` you can never go back without deleting the entire source repo and recloning.

**Comment by dadrian** [comment]
You can `git clean -dfx` and you're fine. You don't have to reclone.

There's no reason to arbitrarily add random subdirectories to our .gitignore. If we want to encourage out of source builds, we should have the examples build to an adjacent directory to the Git repo, and not a magic subdirectory.

**Pull request merged**
