### PR TITLE
Split `send-bsd.h` into `send-mac.h` and `send-bsd.h` and add GitHub action for compiling on FreeBSD/MacOS

### PR DESCRIPTION
**Pull request by phillip-stephens**
- [x] Split up `send-mac.h` from `send-bsh.h` so that each can take advantage of the sys calls available on that OS
- [x] Added GitHub Actions for MacOS and FreeBSD
- [x] Corrected comment that erroneously claimed BSD didn't have sendmmsg

### CODE REVIEW

**Review by zakird — APPROVED** [review]

**Comment by zakird** [comment]
Code looks good, though there's been a bunch of commits post you asking for review, so I'm not 100% sure if it's ready to merge. Can you merge when ready?

**Comment by phillip-stephens** [comment]
Yeahhh. Wanted to test my new Github Action to test compiling on FreeBSD on every PR, but the only way to test was to commit and push and run here. Sooooo, hence the 10k commits lol. I did add the #do-not-review label to try to prevent this 😄

**Comment by phillip-stephens** [comment]
I still have a few things left to do (test using sendmmsg on FreeBSD in a VM), then I'll request a re-review and we can merge. 
cc: @zakird

**Comment by zakird** [comment]
Sounds good. I missed label 🤦🏽 Usually just look at "Draft" status, but will keep my eye out!!

**Pull request merged**
