### PR TITLE
phillip/781: elevate debug log if can't get a socket on bsd to fatal

### PR DESCRIPTION
**Pull request by phillip-stephens**
Noticed in testing this [PR](https://github.com/zmap/zmap/pull/778) that if the user forgets `sudo`, there were a bunch of errors printed on Mac. @droe had the exact same setup but wasn't seeing this behavior, which is odd. Either way, I think this fix makes sense. If you can't get a socket, you can't send packets, so this should be a fatal error, IMO.

### CODE REVIEW

**Comment by droe** [comment]
Concur failure to create socket should lead to a fatal error, two comments:
- `CAP_NET_RAW` mentioned in the error string is a Linux thing and not applicable to macOS or any of the BSDs.
- There are four more failure paths like this one, so I'm thinking a more thorough fix would cover those too.

**Comment by phillip-stephens** [comment]
@droe appreciate your help with this and lending your knowledge of Linux + BSD networking.

1. Thanks, fixed this!
2. Fair, I've addressed. LMK if it looks good to you!

**Comment by droe** [comment]
lgtm, thanks — and thanks for bearing with my PRs!

**Review by zakird — APPROVED** [review]

**Comment by zakird** [comment]
looks good, thank you both!!

**Pull request merged**
