### PR TITLE
MongoDB output module

### PR DESCRIPTION
**Pull request by mschoenlaub**
This PR contains a MongoDB output module.
To build Zmap with support for it, e.g. do 
```
cmake -DWITH_MONGO=ON .
```
The MongoDB connection string must be given in output-args. By default the connection is made to mongodb://localhost:27017/zmap_output.

The collection (analogous to tables in relational DBMS) to be used can be configured via output_filename, the default one is "zmap_output".

### CODE REVIEW

**Comment by dadrian** [comment]
Thanks for the pull request and sorry for the delay in getting back to you. @amirian28, did you ever get a chance to take a look at this?

**Comment by dadrian** [comment]
@mschoenlaub looks pretty good to me! However, it crashes if the zmap scan returns zero results. It'd be nice to fix that before we merge.

**Comment by dadrian** [comment]
Also, sorry about the delay in getting back to you, the ZMap team has been swamped with other things the last few months.

**Comment by mschoenlaub** [comment]
@dadrian : No problem. Issue is fixed now. Sorry for the formatting changes slipped into the commit.

**Comment by dadrian** [comment]
Thanks!

**Pull request merged**
