### PR TITLE
add missing `libnuma-dev` dependency (debian)

### PR DESCRIPTION
**Pull request by azet**

### CODE REVIEW

**Comment by azet** [comment]
Sure!

```

/usr/bin/ld: cannot find -lnuma
collect2: error: ld returned 1 exit status
src/CMakeFiles/ztests.dir/build.make:991: recipe for target 'src/ztests' failed
make[2]: *** [src/ztests] Error 1
CMakeFiles/Makefile2:151: recipe for target 'src/CMakeFiles/ztests.dir/all' failed
make[1]: *** [src/CMakeFiles/ztests.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

works with `libnuma-dev` installed though, full log:

```
azet@scan-sha2017:~/software/zmap/v2.1.1$ cmake .
-- Checking for module 'json-c'
--   Found json-c, version 0.12.1
-- Default ZMap configuration file location is /etc/zmap
-- Checking if blacklist.conf exists there...
-- Checking if zmap.conf exists there...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/azet/software/zmap/v2.1.1
azet@scan-sha2017:~/software/zmap/v2.1.1$ make
[ 20%] Building C object lib/CMakeFiles/zmaplib.dir/blacklist.c.o
[ 20%] Building C object lib/CMakeFiles/zmaplib.dir/constraint.c.o
[ 20%] Building C object lib/CMakeFiles/zmaplib.dir/logger.c.o
[ 20%] Building C object lib/CMakeFiles/zmaplib.dir/pbm.c.o
[ 20%] Building C object lib/CMakeFiles/zmaplib.dir/random.c.o
[ 20%] Building C object lib/CMakeFiles/zmaplib.dir/rijndael-alg-fst.c.o
[ 20%] Building C object lib/CMakeFiles/zmaplib.dir/xalloc.c.o
[ 20%] Building C object lib/CMakeFiles/zmaplib.dir/lockfd.c.o
[ 20%] Building C object lib/CMakeFiles/zmaplib.dir/util.c.o
[ 20%] Building C object lib/CMakeFiles/zmaplib.dir/queue.c.o
[ 20%] Building C object lib/CMakeFiles/zmaplib.dir/csv.c.o
[ 20%] Linking C static library libzmaplib.a
[ 20%] Built target zmaplib
[ 20%] Generating parser.c
[ 20%] Generating ztopt.h
[ 20%] Generating lexer.c
Scanning dependencies of target ztests
[ 20%] Building C object src/CMakeFiles/ztests.dir/aesrand.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/cyclic.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/expression.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/fieldset.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/filter.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/get_gateway.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/iterator.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/monitor.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/recv.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/send.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/shard.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/socket.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/state.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/summary.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/validate.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/ztopt_compat.c.o
In file included from /home/azet/software/zmap/v2.1.1/src/ztopt_compat.c:15:0:
/home/azet/software/zmap/v2.1.1/src/ztopt.c: In function 'update_arg':
/home/azet/software/zmap/v2.1.1/src/ztopt.c:345:15: warning: variable 'val' set but not used [-Wunused-but-set-variable]
   const char *val = value;
               ^~~
/home/azet/software/zmap/v2.1.1/src/ztopt.c:344:9: warning: variable 'stop_char' set but not used [-Wunused-but-set-variable]
   char *stop_char = 0;
         ^~~~~~~~~
/home/azet/software/zmap/v2.1.1/src/ztopt.c: In function 'cmdline_parser_internal':
/home/azet/software/zmap/v2.1.1/src/ztopt.c:414:7: warning: variable 'check_required' set but not used [-Wunused-but-set-variable]
   int check_required;
       ^~~~~~~~~~~~~~
[ 20%] Building C object src/CMakeFiles/ztests.dir/probe_modules/module_icmp_echo.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/probe_modules/module_icmp_echo_time.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/probe_modules/module_tcp_synscan.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/probe_modules/module_tcp_synackscan.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/probe_modules/module_udp.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/probe_modules/packet.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/probe_modules/probe_modules.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/probe_modules/module_ntp.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/probe_modules/module_upnp.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/probe_modules/module_dns.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/probe_modules/module_bacnet.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/output_modules/module_csv.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/output_modules/module_json.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/output_modules/output_modules.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/tests/test_harness.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/lexer.c.o
/home/azet/software/zmap/v2.1.1/src/lexer.c: In function 'yy_get_next_buffer':
/home/azet/software/zmap/v2.1.1/src/lexer.c:586:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for ( n = 0; n < max_size && \
                  ^
/home/azet/software/zmap/v2.1.1/src/lexer.c:1060:3: note: in expansion of macro 'YY_INPUT'
   YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
   ^~~~~~~~
[ 20%] Building C object src/CMakeFiles/ztests.dir/parser.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/socket-pfring.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/recv-pfring.c.o
[ 20%] Linking C executable ztests
/usr/bin/ld: cannot find -lnuma
collect2: error: ld returned 1 exit status
src/CMakeFiles/ztests.dir/build.make:991: recipe for target 'src/ztests' failed
make[2]: *** [src/ztests] Error 1
CMakeFiles/Makefile2:151: recipe for target 'src/CMakeFiles/ztests.dir/all' failed
make[1]: *** [src/CMakeFiles/ztests.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
azet@scan-sha2017:~/software/zmap/v2.1.1$ sudo apt-get install libnuma-dev -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libnuma-dev
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/46.0 kB of archives.
After this operation, 166 kB of additional disk space will be used.
Selecting previously unselected package libnuma-dev:amd64.
(Reading database ... 68098 files and directories currently installed.)
Preparing to unpack .../libnuma-dev_2.0.11-2.1_amd64.deb ...
Unpacking libnuma-dev:amd64 (2.0.11-2.1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libnuma-dev:amd64 (2.0.11-2.1) ...
azet@scan-sha2017:~/software/zmap/v2.1.1$ make -j4
[ 20%] Built target zmaplib
[ 20%] Generating zbopt.h
[ 20%] Built target git_versioning
[ 20%] Generating zitopt.h
[ 20%] Generating zopt.h
[ 20%] Generating ztopt.h
Scanning dependencies of target zblacklist
[ 20%] Building C object src/CMakeFiles/ztests.dir/ztopt_compat.c.o
Scanning dependencies of target zmap
Scanning dependencies of target ziterate
In file included from /home/azet/software/zmap/v2.1.1/src/ztopt_compat.c:15:0:
/home/azet/software/zmap/v2.1.1/src/ztopt.c: In function 'update_arg':
/home/azet/software/zmap/v2.1.1/src/ztopt.c:345:15: warning: variable 'val' set but not used [-Wunused-but-set-variable]
   const char *val = value;
               ^~~
/home/azet/software/zmap/v2.1.1/src/ztopt.c:344:9: warning: variable 'stop_char' set but not used [-Wunused-but-set-variable]
   char *stop_char = 0;
         ^~~~~~~~~
/home/azet/software/zmap/v2.1.1/src/ztopt.c: In function 'cmdline_parser_internal':
/home/azet/software/zmap/v2.1.1/src/ztopt.c:414:7: warning: variable 'check_required' set but not used [-Wunused-but-set-variable]
   int check_required;
       ^~~~~~~~~~~~~~
[ 20%] Building C object src/CMakeFiles/zmap.dir/aesrand.c.o
[ 20%] Building C object src/CMakeFiles/zblacklist.dir/zblacklist.c.o
[ 20%] Building C object src/CMakeFiles/ziterate.dir/aesrand.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/tests/test_harness.c.o
[ 20%] Building C object src/CMakeFiles/ziterate.dir/cyclic.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/cyclic.c.o
[ 20%] Building C object src/CMakeFiles/zblacklist.dir/zbopt_compat.c.o
[ 20%] Building C object src/CMakeFiles/ziterate.dir/iterator.c.o
[ 20%] Linking C executable ztests
In file included from /home/azet/software/zmap/v2.1.1/src/zbopt_compat.c:15:0:
/home/azet/software/zmap/v2.1.1/src/zbopt.c: In function 'cmdline_parser_internal':
/home/azet/software/zmap/v2.1.1/src/zbopt.c:505:7: warning: variable 'check_required' set but not used [-Wunused-but-set-variable]
   int check_required;
       ^~~~~~~~~~~~~~
[ 20%] Building C object src/CMakeFiles/zmap.dir/expression.c.o
[ 20%] Building C object src/CMakeFiles/ziterate.dir/shard.c.o
[ 20%] Built target ztests
[ 20%] Building C object src/CMakeFiles/zmap.dir/fieldset.c.o
[ 20%] Generating topt.h
[ 20%] Linking C executable zblacklist
Scanning dependencies of target ztee
[ 20%] Building C object src/CMakeFiles/ztee.dir/ztee.c.o
[ 20%] Building C object src/CMakeFiles/ziterate.dir/state.c.o
[ 20%] Built target zblacklist
[ 20%] Building C object src/CMakeFiles/zmap.dir/filter.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/get_gateway.c.o
[ 20%] Building C object src/CMakeFiles/ziterate.dir/validate.c.o
[ 20%] Building C object src/CMakeFiles/ztee.dir/topt_compat.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/iterator.c.o
[ 20%] Building C object src/CMakeFiles/ziterate.dir/zitopt_compat.c.o
In file included from /home/azet/software/zmap/v2.1.1/src/topt_compat.c:7:0:
/home/azet/software/zmap/v2.1.1/src/topt.c: In function 'update_arg':
/home/azet/software/zmap/v2.1.1/src/topt.c:397:9: warning: variable 'stop_char' set but not used [-Wunused-but-set-variable]
   char *stop_char = 0;
         ^~~~~~~~~
/home/azet/software/zmap/v2.1.1/src/topt.c: In function 'cmdline_parser_interna':
/home/azet/software/zmap/v2.1.1/src/topt.c:476:7: warning: variable 'check_required' set but not used [-Wunused-but-set-variable]
   int check_required;
       ^~~~~~~~~~~~~~
In file included from /home/azet/software/zmap/v2.1.1/src/zitopt_compat.c:15:0:
/home/azet/software/zmap/v2.1.1/src/zitopt.c: In function 'cmdline_parser_internal':
/home/azet/software/zmap/v2.1.1/src/zitopt.c:545:7: warning: variable 'check_required' set but not used [-Wunused-but-set-variable]
   int check_required;
       ^~~~~~~~~~~~~~
[ 20%] Linking C executable ztee
[ 20%] Building C object src/CMakeFiles/zmap.dir/monitor.c.o
[ 20%] Built target ztee
[ 20%] Building C object src/CMakeFiles/zmap.dir/recv.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/send.c.o
[ 20%] Building C object src/CMakeFiles/ziterate.dir/ziterate.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/shard.c.o
[ 20%] Linking C executable ziterate
[ 20%] Building C object src/CMakeFiles/zmap.dir/socket.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/state.c.o
[ 20%] Built target ziterate
[ 20%] Building C object src/CMakeFiles/zmap.dir/summary.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/validate.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/zmap.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/zopt_compat.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/lexer.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/parser.c.o
In file included from /home/azet/software/zmap/v2.1.1/src/zopt_compat.c:15:0:
/home/azet/software/zmap/v2.1.1/src/zopt.c: In function 'cmdline_parser_interna':
/home/azet/software/zmap/v2.1.1/src/zopt.c:854:7: warning: variable 'check_required' set but not used [-Wunused-but-set-variable]
   int check_required;
       ^~~~~~~~~~~~~~
/home/azet/software/zmap/v2.1.1/src/lexer.c: In function 'yy_get_next_buffer':
/home/azet/software/zmap/v2.1.1/src/lexer.c:586:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for ( n = 0; n < max_size && \
                  ^
/home/azet/software/zmap/v2.1.1/src/lexer.c:1060:3: note: in expansion of macro 'YY_INPUT'
   YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
   ^~~~~~~~
[ 20%] Building C object src/CMakeFiles/zmap.dir/probe_modules/module_icmp_echo.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/probe_modules/module_icmp_echo_time.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/probe_modules/module_tcp_synscan.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/probe_modules/module_tcp_synackscan.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/probe_modules/module_udp.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/probe_modules/packet.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/probe_modules/probe_modules.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/probe_modules/module_ntp.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/probe_modules/module_upnp.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/probe_modules/module_dns.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/probe_modules/module_bacnet.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/output_modules/module_csv.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/output_modules/module_json.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/output_modules/output_modules.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/socket-pfring.c.o
[ 20%] Building C object src/CMakeFiles/zmap.dir/recv-pfring.c.o
[ 20%] Linking C executable zmap
[ 20%] Built target zmap
```

**Comment by paul-pearce** [comment]
I certainly don't have libnuma-dev installed on any of my machines. Can we open an issue for this and investigate? (Perhaps this is a weird debian dependency?)

**Comment by azet** [comment]
It may very well be a weird dependency. Mind this is a current debian testing and installed as bare minimal-install. So there aren't many packages on the machine. I also do not get why the development headers would be of any significance to `ld(1)` - but installing that package solves the issue for me.

**Comment by zakird** [comment]
For some reason, it looks like you're trying to build with PF_RING support. I believe that PF_RING _does_ require libnuma, but the default should not be trying to build with PF_RING support. 

I'm specifically noting:
```
[ 20%] Building C object src/CMakeFiles/ztests.dir/socket-pfring.c.o
[ 20%] Building C object src/CMakeFiles/ztests.dir/recv-pfring.c.o
```

But if you look at the CMake configuration, you'll see
```
# Handle various versions of socket
if(WITH_PFRING)
    set(SOURCES ${SOURCES} socket-pfring.c)
    set(ZTESTSOURCES ${ZTESTSOURCES} socket-pfring.c)
elseif (APPLE OR BSD)
    set(SOURCES ${SOURCES} socket-bsd.c)
    set(ZTESTSOURCES ${ZTESTSOURCES} socket-bsd.c)
else()
    set(SOURCES ${SOURCES} socket-linux.c)
    set(ZTESTSOURCES ${ZTESTSOURCES} socket-linux.c)
endif()
```

So I think this issue should really be: Why is @azet's system think `WITH_PFRING` is set when it's not. 

@azet just to confirm that this isn't something leftover, can you try to clone to a fresh directory and rebuild and see if you're trying to build with PF_RING support?

**Comment by zakird** [comment]
I agree with Paul that this should probably be an issue. Given that we do not want to include `libnuma`, I'm going to close this PR and move this over to an issue.

**Comment by zakird** [comment]
This has been migrated to #447.

**Pull request closed without merging**
