### PR TITLE
Fix packet rate limiting in send.c under specific conditions. Harden send.c

### PR DESCRIPTION
**Pull request by paul-pearce**
(Note: This branch has a bunch of debug and partial commits in it. Once approved let me squash and edit the commit msg down plz.)

This PR fixes a number of issues:

* `count` and `last_count` were type `uint32_t`. When sending multiple packets (`-P`) this could lead to overflow. They are now `uint64_t`
* We implicitly relied on `count > last_count` and `time > last_time`. These are now assertions (that would have caught the overflow above)
* Our carefully calculated `delay` (used for busy waiting) is thrown away on the first iteration through the loop due to a startup error (`count == 0`). This caused delay to begin at `1` and cause a send spike. This is fixed by not entering the delay adjustment clause on startup (`count == 0`)
* The behavior of our delay calculation code is... problematic. If it ever converges to `delay == 1` and `rate` is set to greater than roughly `1/2 MAX`, where MAX is the max rate the system can send at, we lose control of the loop and emit packets at a rate beyond `rate`, never leaving `delay == 1`. Normally, this shouldn't matter, except when `delay` goes to 1 by mistake (or with the bug above). To harden against this, we now `log_fatal` if `delay -> 1`, both as a precaution to prevent emitting packets faster than `rate` (in the case of a bug or a momentary hiccup) but also as a feedback feature, as if you naturally go to `delay -> 1` it means you've specified a `rate` the hardware can't support.

### CODE REVIEW

**Comment by paul-pearce** [comment]
Addresses #475

**Comment by dadrian** [comment]
What happens if you set `-r` close to say, line rate, and hardware supports line rate?

**Comment by paul-pearce** [comment]
@dadrian it should be fine as long as you are not repeatedly under-performing (requesting a rate limit you can't meet) and converging to no delay.

I'm not in a position to test running at such a high rate with our network setup (we'd, um, break stuff). Can you give it a whirl and make sure it's OK?

**Comment by dadrian** [comment]
@paul-pearce just set `-G 00:00:00:00:00:00`

**Comment by dadrian** [comment]
Tested it with near-line-rate speeds on my box. Looks good to me still, although as expected it's less accurate the higher the speed per thread is. Setting `-r 1400000` (1.4Mpps, 0.04 shy of 1gbps), ran at about 1.42Mpps, but adding `-T 2` had a nice and steady 1.4Mpps.

**Pull request merged**
