### PR TITLE
adjusted timing adjustment

### PR DESCRIPTION
**Pull request by zakird**

### CODE REVIEW

**Comment by zakird** [comment]
(WIP)

**Comment by paul-pearce** [comment]
This PR re-introduces the problem of exceeding `-r`.

By changing from `delay < 1` to `delay < 2` you've made it harder for the problem to occur, but it still happens.

To simulate what will occur when delay drops below 2, artificially reset delay to 0 on the first loop with this diff:

```
diff --git a/src/send.c b/src/send.c
index 3fa5652..2bf910b 100644
--- a/src/send.c
+++ b/src/send.c
@@ -298,7 +298,7 @@ int send_run(sock_t st, shard_t *s)
        while (1) {
                // Adaptive timing delay
                send_rate = (double)zconf.rate / zconf.senders;
-               if (count && delay > 0) {
+               if (delay > 0) {
                        if (send_rate < slow_rate) {
                                double t = now();
                                double last_rate = (1.0 / (t - last_time));
```

(This reintroduces the original bug that uncovered the behavior.)

Although this is artificial, you could also recreate it by having a cron or similar that sucks up all CPU usage during a run.

Here's two runs with this branch plus that diff:

```
$ sudo src/zmap -i eth0 -r 540000 -p XXXX > /dev/null
 0:00 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:00 0%; send: 177 431 Kp/s (8.33 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 0%; send: 677263 677 Kp/s (663 Kp/s avg); recv: 808 807 p/s (790 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.12%
 0:02 0%; send: 1218156 541 Kp/s (603 Kp/s avg); recv: 1329 520 p/s (657 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.11%
 0:03 0%; send: 1758325 540 Kp/s (582 Kp/s avg); recv: 1871 541 p/s (619 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.11%
 0:04 0%; send: 2299648 541 Kp/s (572 Kp/s avg); recv: 2331 459 p/s (579 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.10%
 0:05 0% (1h49m left); send: 2840323 540 Kp/s (565 Kp/s avg); recv: 2823 491 p/s (562 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.10%
 0:06 0% (1h49m left); send: 3380997 541 Kp/s (561 Kp/s avg); recv: 3279 455 p/s (544 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.10%
```

We obey the rate limit. Now watch what happens at a higher rate:

```
^Cpearce@researchscan1:~/zmap$ sudo src/zmap -i eth0 -r 640000 -p XXX > /dev/null
 0:00 0%; send: 35 0 p/s (1.82 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:00 0%; send: 194 445 Kp/s (9.91 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 0%; send: 892464 892 Kp/s (875 Kp/s avg); recv: 623 622 p/s (610 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.07%
 0:02 0%; send: 1782911 890 Kp/s (883 Kp/s avg); recv: 1292 668 p/s (639 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.07%
 0:03 0%; send: 2684959 902 Kp/s (889 Kp/s avg); recv: 1976 683 p/s (654 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.07%
 0:04 0%; send: 3584048 899 Kp/s (891 Kp/s avg); recv: 2738 761 p/s (680 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.08%
 0:05 0% (1h09m left); send: 4460052 876 Kp/s (888 Kp/s avg); recv: 3407 668 p/s (678 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.08%
```

We now run at a rate higher than specified. This is the original bug, except now it occurs when `-r` is about 3/4 MAX, instead of 1/2 MAX (with `delay < 1`).

**Comment by zakird** [comment]
new attempt pushed.

**Comment by paul-pearce** [comment]
This new attempt has the same problem as the old one. If the multiplier ever goes too low, you can't recover.

To force multiplier low for 1 cycle, I added the following diff:

```
diff --git a/src/send.c b/src/send.c
index 1f3bcd1..f38a187 100644
--- a/src/send.c
+++ b/src/send.c
@@ -292,6 +292,7 @@ int send_run(sock_t st, shard_t *s)
        }
        int attempts = zconf.num_retries + 1;
        uint32_t idx = 0;
+       uint32_t has_run = 0;
        while (1) {
                // Adaptive timing delay
                send_rate = (double)zconf.rate / zconf.senders;
@@ -320,6 +321,12 @@ int send_run(sock_t st, shard_t *s)
                                                 (t - last_time) /
                                                 (zconf.rate / zconf.senders);
                                        uint32_t old_delay = delay;
+
+                                       if (has_run == 0) {
+                                               multiplier = 0.001;
+                                               has_run = 1;
+                                       }
+
                                        delay *= multiplier;
                                        if (delay == old_delay) {
                                                if (multiplier > 1.0) {
```
At low rate, this is fine:

```
$ sudo src/zmap -i eth0 -r 100000 -p XXX > /dev/null
 0:00 0%; send: 40 0 p/s (1.84 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 0%; send: 121111 121 Kp/s (119 Kp/s avg); recv: 81 80 p/s (79 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.07%
 0:02 0%; send: 211420 90.3 Kp/s (105 Kp/s avg); recv: 134 52 p/s (66 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.06%
 0:03 0%; send: 311521 100 Kp/s (103 Kp/s avg); recv: 210 75 p/s (69 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.07%
 0:04 0%; send: 410859 99.3 Kp/s (102 Kp/s avg); recv: 284 73 p/s (70 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.07%
 0:05 0% (10h left); send: 502156 91.3 Kp/s (100.0 Kp/s avg); recv: 362 77 p/s (72 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.07%
 0:06 0% (10h left); send: 602032 99.8 Kp/s (99.9 Kp/s avg); recv: 465 102 p/s (77 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.08%
 0:07 0% (10h left); send: 697392 95.3 Kp/s (99.3 Kp/s avg); recv: 543 77 p/s (77 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.08%
 0:08 0% (10h left); send: 792729 95.3 Kp/s (98.8 Kp/s avg); recv: 639 95 p/s (79 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.08%
 0:09 0% (10h left); send: 892775 100 Kp/s (98.9 Kp/s avg); recv: 729 89 p/s (80 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.08%
 0:10 0% (10h left); send: 992659 99.9 Kp/s (99.0 Kp/s avg); recv: 824 94 p/s (82 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.08%
```

But at a slightly higher rate, this is catastrophic:

```
$ sudo src/zmap -i eth0 -r 400000 -p XXX > /dev/null
 0:00 0%; send: 13 0 p/s (701 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:00 0%; send: 73 235 Kp/s (3.88 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:01 0%; send: 906194 906 Kp/s (889 Kp/s avg); recv: 907 906 p/s (889 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.10%
 0:02 0%; send: 1859815 953 Kp/s (921 Kp/s avg); recv: 1728 820 p/s (855 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.09%
 0:03 0%; send: 2813308 953 Kp/s (932 Kp/s avg); recv: 2537 808 p/s (840 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.09%
 0:04 0%; send: 3765448 952 Kp/s (937 Kp/s avg); recv: 3322 784 p/s (826 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.09%
 0:05 0% (1h05m left); send: 4704393 939 Kp/s (937 Kp/s avg); recv: 4129 806 p/s (822 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.09%
 0:06 0% (1h06m left); send: 5614391 910 Kp/s (933 Kp/s avg); recv: 4877 747 p/s (810 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.09%
```

**Comment by jhart-r7** [comment]
Is there anything I can do to help with this bug?

**Comment by paul-pearce** [comment]
I think this is squarely in our court. We're all just a bit overloaded at the moment.

Are you blocked on this? I'd hope up'ing the threads resolved your issue?

**Comment by jhart-r7** [comment]
@paul-pearce I wouldn't say blocked, but from what I recall of the several issues and PRs is that zmap still exceeds its configured rate/bandwidth scenarios which we seem adept at hitting ;).  I'll give current master and maybe this PR another test and see what I can find to refresh my memory of the state of things.

**Pull request merged**
