### PR TITLE
build: improve Dockerfile

### PR DESCRIPTION
**Pull request by developStorm**
* Use multi-stage building to reduce image size
* Add GitHub Action to automatically publish image on [GitHub container registry](https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages)

### CODE REVIEW

**Review by dadrian — APPROVED** [review]

**Comment by developStorm** [comment]
@dadrian Thanks for approving this! Just want to give a heads up that I don't have merge access to the branch so a maintainer probably has to merge this.

image

**Comment by dadrian** [comment]
@developStorm Yeah, I just got distracted and hadn't clicked the button yet. Thanks for the PR!

**Comment by developStorm** [comment]
@dadrian You're welcome! I was monitoring the action run and looks like it succeeded. For some reason, I think the packge is set to private now so I can't test it -- could you make it public so that everyone can pull the image?

The package should have been listed on your side as shown:
image

Thanks!

**Comment by dadrian** [comment]
It should be visible now.

**Pull request merged**
